# fly.toml file generated for showdown-labs-keydb-fly on 2022-01-30T17:38:09-05:00

app = "showdown-labs-keydb-fly"

kill_signal = "SIGTERM"
kill_timeout = 120

[mount]
destination = "/data"
source = "keydb_server"

[metrics]
port = 9091
path = "/metrics"
